name: Acilia Backend Tests

on:
  pull_request:
  push:
    branches:
      - master
      #- main

jobs:
  php-unit:
    name: PHP Unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP version
        uses: shivammathur/setup-php@2.7.0
        with:
          coverage: "none"
          extensions: "intl, mbstring, pdo_sqlite"
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Add PHPUnit matcher
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Set Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2.1.2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

      - name: Require symfony/flex
        run: composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-main

      - run: composer update

      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit install

      - name: Run tests
        run: vendor/bin/simple-phpunit
