name: Acilia Frontend Linters

on:
  push:
    branches:
      - master
      #- main
  pull_request:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn install

      - name: Run ESLint
        run: yarn run eslint assets/ --ext .js,.jsx,.ts,.tsx
